import hashlib
import logging
import time
from datetime import timedelta

from fastapi import APIRouter
from sqlalchemy import func, select
from sqlalchemy.ext.asyncio import AsyncSession

from src.api.deps import CurrentUserIdDep, DbSessionDep, SettingsDep, get_pipeline_for
from src.clients import get_redis, publish_event
from src.config import Settings
from src.core.errors import GuardrailViolation
from src.db import ChatAuditLog, ChatHistory
from src.guardrails import mask_pii
from src.pipeline.pricing import SESSION_DAILY_BUDGET_USD
from src.schemas import ChatRequest, ChatResponse

router = APIRouter(tags=["chat"])
log = logging.getLogger(__name__)


def _cache_key(settings: Settings, req: ChatRequest, question_masked: str) -> str:
    # Mode is part of the key so switching USE_STUBS/ANTHROPIC_API_KEY, or picking a different
    # model in the UI, never serves a cached answer generated by a different mode/model.
    provider = req.llm_provider or settings.llm_provider
    model = req.llm_model or settings.llm_model
    mode = f"{settings.use_stubs}:{bool(settings.anthropic_api_key)}:{provider}:{model}"
    digest = hashlib.sha256(question_masked.strip().lower().encode()).hexdigest()
    return f"chat:{mode}:{digest}"


async def _get_cached(key: str) -> ChatResponse | None:
    try:
        raw = await get_redis().get(key)
    except Exception:
        log.warning("Redis unavailable; skipping response cache lookup", exc_info=True)
        return None
    return ChatResponse.model_validate_json(raw) if raw else None


async def _set_cached(key: str, response: ChatResponse, ttl_seconds: int) -> None:
    try:
        await get_redis().set(key, response.model_dump_json(), ex=ttl_seconds)
    except Exception:
        log.warning("Redis unavailable; response was not cached", exc_info=True)


async def _record(
    db: AsyncSession,
    req: ChatRequest,
    user_id: int | None,
    question_masked: str,
    answer: str,
    citations_count: int,
    sources_queried: str,
    outcome: str,
    duration_ms: float,
    cost_usd: float | None = None,
) -> None:
    """Best-effort: a Postgres outage degrades history/audit logging, it must never fail the
    chat response itself."""
    try:
        db.add(ChatHistory(session_id=req.session_id, user_id=user_id, question_masked=question_masked, answer=answer))
        db.add(
            ChatAuditLog(
                session_id=req.session_id,
                user_id=user_id,
                question_masked=question_masked,
                answer=answer,
                sources_queried=sources_queried,
                citations_count=citations_count,
                outcome=outcome,
                duration_ms=duration_ms,
                cost_usd=cost_usd,
            )
        )
        await db.commit()
    except Exception:
        log.warning("Could not write chat history/audit log", exc_info=True)
        await db.rollback()


async def _session_spend_24h(db: AsyncSession, session_id: str) -> float | None:
    """Best-effort, like every other platform read on this path: `None` on any failure means
    "can't check right now", which the caller treats as "don't block" -- a Postgres outage must
    degrade this the same way it degrades history/audit logging, never the chat response itself.

    The 24h cutoff is computed from the database's *own* current time (`SELECT now()`, then
    subtracting the window in Python) rather than a Python-side `datetime.now()`, so it can never
    disagree with whatever wrote `created_at` (`server_default=func.now()`) -- the exact bug this
    sidesteps was caught live while building evals/check_alerts.py (see CLAUDE.md): a client
    clock that disagreed with the Postgres server's by several hours silently returned zero rows.
    """
    try:
        # Postgres's now() returns a tz-aware `timestamptz` value through asyncpg regardless of
        # created_at's own (naive) column type -- confirmed live: asyncpg rejects the bind
        # param outright ("can't subtract offset-naive and offset-aware datetimes") without the
        # explicit strip below. SQLite (tests, via the db_session fixture) returns a naive
        # value already, so .replace() is a no-op there.
        server_now = (await db.execute(select(func.now()))).scalar_one().replace(tzinfo=None)
        cutoff = server_now - timedelta(hours=24)
        result = await db.execute(
            select(func.sum(ChatAuditLog.cost_usd)).where(
                ChatAuditLog.session_id == session_id, ChatAuditLog.created_at >= cutoff
            )
        )
        total = result.scalar()
        return float(total) if total is not None else 0.0
    except Exception:
        log.warning("Could not read session spend; skipping the session budget check", exc_info=True)
        return None


@router.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest, db: DbSessionDep, settings: SettingsDep, user_id: CurrentUserIdDep) -> ChatResponse:
    pipeline = get_pipeline_for(req.llm_provider, req.llm_model, req.allow_actions)
    # Masked independently of the pipeline's own "pii" stage: this is for logging/caching, and
    # must hold even on paths (guardrail block, error) where the pipeline never gets that far.
    question_masked = mask_pii(req.message)
    key = _cache_key(settings, req, question_masked)

    # Never cache (read or write) an actions-enabled request: a cached ChatResponse's
    # proposed_action_ids point at proposals tied to the session that *first* asked this
    # question -- replaying it for a different session would hand back someone else's pending
    # proposal ids, which is wrong regardless of whether Redis itself is trustworthy.
    cached = None if req.allow_actions else await _get_cached(key)
    if cached is not None:
        await _record(
            db,
            req,
            user_id,
            question_masked,
            cached.answer,
            len(cached.citations),
            "",
            "success_cached",
            0.0,
            cost_usd=cached.total_cost_usd,
        )
        return cached

    # Session-level circuit breaker (README's "Job-level limits"): once a session has spent its
    # rolling-24h budget, force the answerer's pre-flight budget to 0 for this request -- the
    # existing per-request budget-rejection path (src/pipeline/answering/agent.py) then degrades
    # to the context-only fallback answer, same as any other over-budget request, rather than a
    # new failure mode. `session_spend` is None when it couldn't be checked (DB down); that
    # means "don't block", not "assume under budget forever" -- same best-effort treatment as
    # every other platform read on this path.
    session_spend = await _session_spend_24h(db, req.session_id)
    max_answer_cost_usd = 0.0 if session_spend is not None and session_spend >= SESSION_DAILY_BUDGET_USD else None
    if max_answer_cost_usd == 0.0:
        log.warning(
            "session=%s spent $%.4f in the last 24h, over the $%.2f cap; forcing a free response",
            req.session_id,
            session_spend,
            SESSION_DAILY_BUDGET_USD,
        )

    start = time.perf_counter()
    try:
        response = await pipeline.run(req, max_answer_cost_usd=max_answer_cost_usd)
    except GuardrailViolation:
        duration_ms = round((time.perf_counter() - start) * 1000, 1)
        await _record(db, req, user_id, question_masked, "", 0, "", "guardrail_blocked", duration_ms)
        raise
    except Exception:
        duration_ms = round((time.perf_counter() - start) * 1000, 1)
        await _record(db, req, user_id, question_masked, "", 0, "", "error", duration_ms)
        raise
    duration_ms = round((time.perf_counter() - start) * 1000, 1)

    if not req.allow_actions:
        await _set_cached(key, response, settings.response_cache_ttl_seconds)
    sources_queried = ",".join(sorted({c.source_type for c in response.citations}))
    await _record(
        db,
        req,
        user_id,
        question_masked,
        response.answer,
        len(response.citations),
        sources_queried,
        "success",
        duration_ms,
        cost_usd=response.total_cost_usd,
    )
    await publish_event(
        "rivet.chat.completed",
        {
            "session_id": req.session_id,
            "user_id": user_id,
            "citations": len(response.citations),
            "sources_queried": sources_queried,
            "duration_ms": duration_ms,
        },
    )
    return response
